# Set keyboard to UK
setxkbmap gb &

# Statusbar
dwm-bar &

# Statusbar applets
nm-applet &
discord --start-minimized &

# Change wallpaper
wal -i /home/$USER/media/Pictures/Wallpapers

# Dunst
/home/$USER/.config/dunst/wal.sh &

# Build st
cd /home/$USER/.config/st
sudo make clean install

# Build dmenu
cd /home/$USER/.config/dmenu
sudo make clean install

# Build dwm
cd /home/$USER/.config/dwm
sudo make clean install
cd /home/$USER

# Start dwm
picom --config ~/.config/picom/picom.conf -b
exec dwm
